begin;
create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions, pg_temp;
select plan(14);
select has_function('public','aura_llm_reserve_call_v1',array['uuid','integer','integer','integer','integer','integer'],'atomic provider quota RPC exists');
select has_function('public','aura_inventory_lot_lookup_v1',array['text','text','integer'],'bounded lot lookup exists');
select ok(not has_schema_privilege('anon','aura_private','usage'),'anonymous cannot access quota schema');
select ok(not has_schema_privilege('authenticated','aura_private','usage'),'browser cannot access quota schema');
select ok((select relrowsecurity from pg_class where oid='aura_private.llm_provider_calls'::regclass),'quota ledger has RLS');
select ok(not has_function_privilege('anon','public.aura_llm_reserve_call_v1(uuid,integer,integer,integer,integer,integer)','execute'),'anonymous cannot reserve quota');
select ok(not has_function_privilege('authenticated','public.aura_llm_reserve_call_v1(uuid,integer,integer,integer,integer,integer)','execute'),'browser cannot reserve quota');
select ok(has_function_privilege('service_role','public.aura_llm_reserve_call_v1(uuid,integer,integer,integer,integer,integer)','execute'),'authorized server can reserve quota');
select ok(not has_function_privilege('authenticated','public.aura_inventory_lot_lookup_v1(text,text,integer)','execute'),'browser cannot bypass lot authorization');
select ok(not (select prosecdef from pg_proc where oid='public.aura_inventory_lot_lookup_v1(text,text,integer)'::regprocedure),'lot lookup preserves invoker privileges');
select ok((select proconfig @> array['statement_timeout=4s'] from pg_proc where oid='public.aura_inventory_lot_lookup_v1(text,text,integer)'::regprocedure),'lot lookup uses bounded SQL time');
select has_index('public','ph_master_inventory','idx_ph_master_inventory_aura_lot_uid','lot keyset is indexed');
delete from aura_private.llm_provider_calls;
set local role service_role;
select is((public.aura_llm_reserve_call_v1('00000000-0011-4000-8000-000000000001',1,100,15,1000000,1500)->>'allowed')::boolean,true,'service reservation succeeds');
select is((public.aura_llm_reserve_call_v1('00000000-0011-4000-8000-000000000001',1,100,15,1000000,1500)->>'duplicate')::boolean,true,'same provider attempt cannot execute twice');
reset role;
select * from finish();
rollback;
