begin;
create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions, pg_temp;
select plan(19);
select has_table('aura_private','aura_query_conversations','conversation memory is private');
select has_table('aura_private','aura_query_turns','turn memory is private');
select ok((select relrowsecurity from pg_class where oid='aura_private.aura_query_conversations'::regclass),'conversation memory has RLS');
select ok((select relrowsecurity from pg_class where oid='aura_private.aura_query_turns'::regclass),'turn memory has RLS');
select ok(not has_schema_privilege('anon','aura_private','usage'),'anonymous cannot access private memory');
select ok(not has_schema_privilege('authenticated','aura_private','usage'),'browser cannot access private memory');
select ok(not has_table_privilege('service_role','aura_private.aura_query_conversations','select'),'service calls cannot bypass actor RPC');
select ok(not has_table_privilege('service_role','aura_private.aura_query_turns','select'),'turns cannot be read outside actor RPC');
select ok(not has_function_privilege('anon','public.aura_query_conversation_v1(uuid,text,uuid,uuid,integer,jsonb)','execute'),'anonymous cannot read conversation RPC');
select ok(not has_function_privilege('authenticated','public.aura_query_conversation_v1(uuid,text,uuid,uuid,integer,jsonb)','execute'),'browser cannot call conversation RPC');
select ok(has_function_privilege('service_role','public.aura_query_conversation_v1(uuid,text,uuid,uuid,integer,jsonb)','execute'),'server can call conversation RPC');
select ok((select prosecdef from pg_proc where oid='public.aura_query_conversation_v1(uuid,text,uuid,uuid,integer,jsonb)'::regprocedure),'conversation RPC enforces actor gate as definer');
select ok((select proconfig @> array['statement_timeout=5s'] from pg_proc where oid='public.aura_query_conversation_v1(uuid,text,uuid,uuid,integer,jsonb)'::regprocedure),'conversation RPC has bounded execution');
select ok((select prosrc like '%navigation_module_allowed_v1%' and prosrc like '%drive%' from pg_proc where oid='public.aura_query_inventory_v1(uuid,text,jsonb,jsonb,integer)'::regprocedure),'inventory RPC enforces the Drive module ACL');
select ok((select prosrc like '%navigation_module_allowed_v1%' and prosrc like '%hl-order%' from pg_proc where oid='public.aura_query_hl_order_v1(uuid,text,jsonb,jsonb,integer)'::regprocedure),'HL order RPC enforces the HL Order module ACL');
select has_function('public','aura_query_inventory_v1',array['uuid','text','jsonb','jsonb','integer'],'typed inventory RPC exists');
select has_function('public','aura_query_hl_order_v1',array['uuid','text','jsonb','jsonb','integer'],'read-only order RPC exists');
select ok(not has_function_privilege('authenticated','public.aura_query_inventory_v1(uuid,text,jsonb,jsonb,integer)','execute'),'browser cannot call inventory RPC directly');
select ok(not has_function_privilege('authenticated','public.aura_query_hl_order_v1(uuid,text,jsonb,jsonb,integer)','execute'),'browser cannot call order RPC directly');
select * from finish();
rollback;
