begin;

alter table if exists public.v2_app_users
    add column if not exists password_hash text,
    add column if not exists password_salt text,
    add column if not exists password_changed_at timestamptz,
    add column if not exists password_expires_at timestamptz,
    add column if not exists must_change_password boolean not null default false,
    add column if not exists failed_login_count integer not null default 0,
    add column if not exists locked_until timestamptz,
    add column if not exists disabled_at timestamptz,
    add column if not exists last_login_at timestamptz;

update public.v2_app_users
set
    must_change_password = true,
    password_expires_at = now()
where upper(coalesce(password, '')) in ('GREENLEAF25', '1234', '12345', 'WELCOME', 'PASSWORD');

create table if not exists public.v2_security_audit_events (
    id bigint generated by default as identity primary key,
    username text,
    event_type text not null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_v2_security_audit_events_username_created
    on public.v2_security_audit_events (lower(username), created_at desc);

create index if not exists idx_v2_security_audit_events_type_created
    on public.v2_security_audit_events (event_type, created_at desc);

create index if not exists idx_v2_app_users_password_expiry
    on public.v2_app_users (password_expires_at)
    where password_expires_at is not null;

create index if not exists idx_v2_app_users_locked_until
    on public.v2_app_users (locked_until)
    where locked_until is not null;

alter table public.v2_security_audit_events enable row level security;

drop policy if exists "service role can read security audit" on public.v2_security_audit_events;
create policy "service role can read security audit"
on public.v2_security_audit_events
for select
to service_role
using (true);

drop policy if exists "service role can write security audit" on public.v2_security_audit_events;
create policy "service role can write security audit"
on public.v2_security_audit_events
for insert
to service_role
with check (true);

alter table public.v2_app_users enable row level security;

drop policy if exists "service role can manage app users" on public.v2_app_users;
create policy "service role can manage app users"
on public.v2_app_users
for all
to service_role
using (true)
with check (true);

comment on column public.v2_app_users.password is
    'Legacy plaintext password column. app-api clears this after password change or opportunistic migration. Do not expose it to the browser.';

comment on column public.v2_app_users.password_hash is
    'PBKDF2-SHA256 password hash generated by app-api. Browser clients must never read this column.';

comment on table public.v2_security_audit_events is
    'Security audit events written by app-api for login, password, lockout, Outlook, and sensitive app actions.';

commit;
