-- CI-only legacy table contract used by provision_native_auth_app_user.
-- Production owns this pre-migration table; the isolated test database did not.
-- Keep only the fields read/written by the existing provisioning RPC. The
-- password-bearing table is service-only, never an authenticated browser API.
create table public.ph_app_users (
  id integer generated by default as identity primary key,
  username text not null,
  password text,
  role text,
  password_hash text,
  password_salt text,
  password_changed_at timestamptz,
  must_change_password boolean,
  failed_login_count integer,
  locked_until timestamptz,
  disabled_at timestamptz,
  division text,
  language text
);

alter table public.ph_app_users enable row level security;
revoke all on table public.ph_app_users from public, anon, authenticated;
revoke all on sequence public.ph_app_users_id_seq from public, anon, authenticated;
grant select, insert, update, delete on table public.ph_app_users to service_role;
grant usage, select on sequence public.ph_app_users_id_seq to service_role;
