import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';

// Isolated PostgreSQL semantics check for the new password-reconciliation SQL.
// PGlite is local-only here and uses the real pgcrypto extension for Auth parity.
const require = createRequire(import.meta.url);
const { PGlite } = require(path.resolve('.gnc-local/pglite/node_modules/@electric-sql/pglite'));
const { pgcrypto } = require(path.resolve('.gnc-local/pglite/node_modules/@electric-sql/pglite/dist/contrib/pgcrypto.cjs'));
const db = new PGlite({ extensions: { pgcrypto } });
const fixture = `
create role anon; create role authenticated; create role service_role;
create schema auth; create schema private; create schema extensions;
create table auth.users(
  id uuid primary key, email text, email_confirmed_at timestamptz,
  raw_app_meta_data jsonb not null default '{}', raw_user_meta_data jsonb not null default '{}',
  encrypted_password text, banned_until timestamptz
);
create table public.ph_app_users(
  id integer generated by default as identity primary key,
  username text not null, password text, role text, password_hash text, password_salt text,
  password_changed_at timestamptz, must_change_password boolean, failed_login_count integer,
  locked_until timestamptz, disabled_at timestamptz, division text, language text
);
create table public.profiles(
  id uuid primary key references auth.users(id) on delete cascade,
  legacy_user_id integer unique, username text not null unique, display_name text,
  role text not null default 'User', division text not null default '10', language text not null default 'English',
  disabled_at timestamptz, locked_until timestamptz, must_change_password boolean not null default false,
  updated_at timestamptz not null default now()
);
create extension pgcrypto with schema extensions;
`;
const check = async (sql, params = []) => (await db.query(sql, params)).rows;
const assert = (condition, message) => { if (!condition) throw new Error(message); };
async function runSqlContractTests() {
  const tapDb = new PGlite({ extensions: { pgcrypto } });
  try {
    await tapDb.exec(fixture);
    const migration = fs.readFileSync(path.resolve('supabase/archive_migrations/20260929160000_password_change_profile_reconciliation.sql'), 'utf8');
    await tapDb.exec(migration);
    await tapDb.exec(`
      create temp table tap_state(expected integer, actual integer default 0);
      create function public.plan(integer) returns text language plpgsql as $$ begin insert into tap_state(expected) values ($1); return 'plan'; end $$;
      create function public.ok(boolean,text) returns text language plpgsql as $$ begin
        update tap_state set actual=actual+1; if not coalesce($1,false) then raise exception 'pgTAP assertion failed: %',$2; end if; return 'ok'; end $$;
      create function public.is(anyelement,anyelement,text) returns text language plpgsql as $$ begin
        update tap_state set actual=actual+1; if $1 is distinct from $2 then raise exception 'pgTAP assertion failed: % (got %, expected %)',$3,$1,$2; end if; return 'ok'; end $$;
      create function public.has_function(text,text,text[],text) returns text language plpgsql as $$ declare sig text; begin
        sig := $1||'.'||$2||'('||array_to_string($3,',')||')';
        return public.ok(to_regprocedure(sig) is not null,$4);
      end $$;
      create function public.throws_ok(text,text,text,text) returns text language plpgsql as $$ declare got_state text; got_message text; begin
        update tap_state set actual=actual+1;
        begin execute $1; exception when others then get stacked diagnostics got_state=returned_sqlstate,got_message=message_text; end;
        if got_state is distinct from $2 or got_message is distinct from $3 then
          raise exception 'pgTAP throws_ok failed: % (got state %, message %)',$4,got_state,got_message;
        end if; return 'ok'; end $$;
      create function public.finish() returns setof text language plpgsql as $$ declare s tap_state%rowtype; begin
        select * into s from tap_state; if s.actual is distinct from s.expected then
          raise exception 'pgTAP planned %, executed % assertions',s.expected,s.actual;
        end if; return next 'all assertions passed'; end $$;
    `);
    const testSql = fs.readFileSync(path.resolve('supabase/tests/password_change_profile_reconciliation_test.sql'), 'utf8')
      .replace('create extension if not exists pgtap with schema extensions;', '');
    await tapDb.exec(testSql);
  } finally {
    await tapDb.close();
  }
}
let stage = 'startup';

try {
  stage = 'fixture';
  await db.exec(fixture);
  stage = 'migration';
  const migration = fs.readFileSync(path.resolve('supabase/archive_migrations/20260929160000_password_change_profile_reconciliation.sql'), 'utf8');
  await db.exec(migration);

  stage = 'deferred identity and synchronization';
  const inserted = await check(`insert into public.ph_app_users(username,password,role,division,language,must_change_password,failed_login_count)
    values('pglite_password_reset','1234','Manager','12','English',false,3) returning id`);
  const legacyId = inserted[0].id;
  const first = (await check(`select * from public.prepare_password_change_profile($1,null,$2)`, ['pglite_password_reset', 'a'.repeat(64)]))[0];
  assert(first.status === 'needs_native_identity' && first.attempt_id, 'starter password without flag must reserve a deferred attempt');
  assert((await check('select must_change_password from public.ph_app_users where id=$1', [legacyId]))[0].must_change_password === true, 'prepare must raise the normal reset gate');

  await db.query(`insert into auth.users(id,email,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,encrypted_password)
    values($1,$2,now(),$3,'{"username":"untrusted-user-metadata"}','starter-hash')`, [
    'd1000000-0000-4000-8000-000000000001', 'pglite_password_reset@greenleafnursery.com',
    JSON.stringify({ role: 'Manager', legacy_user_id: String(legacyId) }),
  ]);
  const ready = (await check(`select * from public.prepare_password_change_profile($1,$2,$3)`, [
    '', 'd1000000-0000-4000-8000-000000000001', 'a'.repeat(64),
  ]))[0];
  assert(ready.status === 'ready' && ready.attempt_id === first.attempt_id, 'trusted Auth retry must reuse and bind the same attempt');
  assert(ready.profile_id === 'd1000000-0000-4000-8000-000000000001' && ready.role === 'Manager', 'missing profile uses verified Auth ID and legacy role');

  await db.query("update auth.users set encrypted_password=extensions.crypt($1,extensions.gen_salt('bf')) where id=$2", ['Next-Pass-2026!', ready.profile_id]);
  const completed = (await check(`select * from public.complete_password_change_profile($1,$2,$3,$4)`, [
    ready.attempt_id, ready.profile_id, 'Next-Pass-2026!', 'a'.repeat(64),
  ]))[0];
  assert(completed.status === 'completed' && completed.must_change_password === false, 'completion returns the current profile with the gate cleared');
  const synced = (await check('select password,must_change_password,failed_login_count from public.ph_app_users where id=$1', [legacyId]))[0];
  assert(synced.password === 'Next-Pass-2026!' && synced.must_change_password === false && synced.failed_login_count === 3, 'completion synchronizes password without clearing unrelated restrictions');
  const replay = (await check(`select * from public.prepare_password_change_profile($1,$2,$3)`, [
    'pglite_password_reset', ready.profile_id, 'a'.repeat(64),
  ]))[0];
  assert(replay.status === 'completed' && replay.role === 'Manager', 'same password retry after lost response is recognized');

  stage = 'profile-link preservation';
  const linkedLegacy = await check(`insert into public.ph_app_users(username,password,role,must_change_password)
    values('pglite_orphan_profile','starter','LegacyRole',true) returning id`);
  const linkedId = linkedLegacy[0].id;
  await db.query(`insert into auth.users(id,email,email_confirmed_at,raw_app_meta_data,encrypted_password)
    values($1,$2,now(),$3,'starter-hash')`, [
    'd1000000-0000-4000-8000-000000000002', 'pglite_orphan_profile@greenleafnursery.com',
    JSON.stringify({ legacy_user_id: String(linkedId) }),
  ]);
  await db.query(`insert into public.profiles(id,username,display_name,role,division,language,must_change_password)
    values($1,'pglite_orphan_profile','Saved Name','SavedRole','42','Spanish',true)`, ['d1000000-0000-4000-8000-000000000002']);
  const orphan = (await check(`select * from public.prepare_password_change_profile($1,$2,$3)`, [
    'pglite_orphan_profile', 'd1000000-0000-4000-8000-000000000002', 'b'.repeat(64),
  ]))[0];
  const savedProfile = (await check('select legacy_user_id,display_name,role,division from public.profiles where id=$1', [orphan.profile_id]))[0];
  assert(orphan.status === 'ready' && savedProfile.legacy_user_id === linkedId, 'orphan profile receives its verified missing link');
  assert(savedProfile.display_name === 'Saved Name' && savedProfile.role === 'SavedRole' && savedProfile.division === '42', 'repair preserves saved profile attributes');

  stage = 'failure guards';
  const duplicate = await check(`insert into public.ph_app_users(username,password,role,must_change_password)
    values('pglite_duplicate','1234','User',true),('PGLITE-DUPLICATE','1234','User',true) returning id`);
  const dupError = await db.query(`select * from public.prepare_password_change_profile('pglite_duplicate',null,$1)`, ['c'.repeat(64)]).then(() => null, error => error);
  assert(duplicate.length === 2 && String(dupError?.message || '').includes('password_change_duplicate_legacy_username'), `normalized duplicate legacy identities must be rejected (got ${dupError?.message || 'no error'})`);
  const wrongPass = await db.query(`select * from public.complete_password_change_profile($1,$2,$3,$4)`, [
    ready.attempt_id, ready.profile_id, 'Wrong-Pass-2026!', 'a'.repeat(64),
  ]).then(() => null, error => error);
  assert(String(wrongPass?.message || '').includes('password_change_auth_password_mismatch'), 'complete must confirm native Auth already has the requested password');

  stage = 'full pgTAP SQL contract';
  await runSqlContractTests();

  console.log('PGlite password reconciliation passed: focused behavior checks and all 56 SQL contract assertions.');
} catch (error) {
  console.error(`PGlite password reconciliation failed during ${stage}: ${error.stack || error.message}`);
  process.exitCode = 1;
} finally {
  await db.close();
}
