// Isolated execution of the actual request archive migration. Never connects remotely.
// node supabase/ci/request_archive_pglite.mjs --pglite-root .gnc-local/pglite
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';

const args = process.argv.slice(2);
const dependencyRoot = args[args.indexOf('--pglite-root') + 1];
if (!args.includes('--pglite-root') || !dependencyRoot) throw Error('Pass --pglite-root');
const { PGlite } = createRequire(path.join(path.resolve(dependencyRoot), 'package.json'))('@electric-sql/pglite');
const db = new PGlite();
const actor = '11111111-1111-4111-8111-111111111111';
const deniedActor = '22222222-2222-4222-8222-222222222222';
const migration = fs.readFileSync(new URL('../migrations/20261001215511_request_archive_005.sql', import.meta.url), 'utf8');
const query = async (sql, params = []) => (await db.query(sql, params)).rows;

const requestTextColumns = [
  'unique_id','master_id','commonname','contsize','locationcode','lotcode','itemcode','ptravailable','season_supply','priority',
  'qualitycode','field_tag_color','plantgroupcode','requested_by','request_folder','req_customer','req_qty','desired_spec',
  'desired_caliper','est_ship','req_reserve','req_photo_link','req_photo_name','req_status','req_rep_action','req_match',
  'req_spec','req_caliper','req_pic_note','req_sales_note','req_comments','av_note','date_completed','req_photo_mode',
  'request_note','request_created_by_username','request_created_by_display','request_created_by_email',
  'request_selected_rep_username','request_selected_rep_display','request_selected_rep_email','request_source',
  'client_batch_id','app_tab_assignment','master_app_tab_assignment','customeridentityid','customername',
  'consigneeidentityid','consigneename'
];

try {
  await db.exec(`
    create role anon; create role authenticated; create role service_role;
    create schema private; create schema auth;
    create table public.profiles(id uuid primary key, username text not null, role text not null);
    create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
    create function private.can_manage_requests() returns boolean language sql stable security definer set search_path = '' as $$
      select exists(select 1 from public.profiles p where p.id = auth.uid() and p.role = 'manager')
    $$;
    create table public.ph_active_request (
      id bigint generated by default as identity primary key,
      ${requestTextColumns.map((column) => `${column} text`).join(',\n      ')},
      req_archived boolean not null default false,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now(),
      row_version bigint not null default 1
    );
    create table public.ph_request_history(unique_id text primary key, delivery_state text, history_event text,
      req_archived boolean not null default false, req_status text, lotcode text, snapshot jsonb not null default '{}'::jsonb);
    create table private.folder_completion_calls(folder_name text not null);
    create table private.history_upsert_calls(unique_id text not null);
    create function private.upsert_request_history(p_uid text, p_event text, p_delivery text, p_recovered boolean)
    returns void language plpgsql security definer set search_path = '' as $$
    begin
      insert into private.history_upsert_calls(unique_id) values(p_uid);
      insert into public.ph_request_history(unique_id, delivery_state, history_event, req_archived, req_status, lotcode, snapshot)
      values(p_uid, p_delivery, p_event, false, 'Pending', 'canonical-lot', jsonb_build_object('source','canonical'))
      on conflict(unique_id) do nothing;
    end $$;
    create function private.reconcile_request_folder_completion_v2(p_folder text) returns void
    language plpgsql security definer set search_path = '' as $$
    begin insert into private.folder_completion_calls(folder_name) values (p_folder); end $$;
    create function private.reconcile_request_folder_from_request_v2() returns trigger
    language plpgsql security definer set search_path = '' as $$
    begin
      if tg_op = 'UPDATE' and current_setting('app.request_archive_transition', true) = 'on' then return new; end if;
      if tg_op = 'UPDATE' and old.req_archived is distinct from new.req_archived then
        perform private.reconcile_request_folder_completion_v2(new.request_folder);
      end if;
      return new;
    end $$;
    create trigger request_folder_reconcile after update on public.ph_active_request
    for each row execute function private.reconcile_request_folder_from_request_v2();
    insert into public.profiles values
      ('${actor}', 'allowed_manager', 'manager'),
      ('${deniedActor}', 'floor_sales', 'sales');
    insert into public.ph_active_request(unique_id, commonname, contsize, locationcode, lotcode, req_archived, req_status, created_at)
      values ('active-1','Elm','#3','A.01','27.F1',false,'Pending',now()),
             ('done-1','Maple','#5','B.02','26.F1',false,'Completed',now()),
             ('archived-1','Ash','#7','C.03','27.F1',true,'Pending',now()-interval '1 day');
    insert into public.ph_request_history(unique_id, delivery_state, history_event, req_archived, req_status, lotcode, snapshot)
      values ('active-1','delivered','created',false,'Original status','historical-lot',jsonb_build_object('original','keep'));
  `);
  await db.exec(migration);

  const setActor = async (id) => query("select set_config('request.jwt.claim.sub', $1, false)", [id]);
  const allowed = async (sql, params = []) => {
    await db.exec('set role service_role');
    try { return await query(sql, params); }
    finally { await db.exec('reset role'); }
  };
  await setActor(actor);
  const firstKey = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
  const archived = (await allowed('select public.request_archive_command_v1($1,$2,$3,$4) data', [actor,'active-1','archive',firstKey]))[0].data;
  assert.equal(archived.state, 'archived');
  assert.equal(archived.row.req_archived, true);
  assert.equal(archived.row.req_status, 'Pending');
  assert.equal(archived.row.date_completed, null);
  const historyBefore = { delivery_state: 'delivered', history_event: 'created', req_archived: false, req_status: 'Original status', lotcode: 'historical-lot', snapshot: { original: 'keep' } };
  assert.deepEqual((await query("select delivery_state, history_event, req_archived, req_status, lotcode, snapshot from public.ph_request_history where unique_id='active-1'"))[0], historyBefore);
  assert.equal((await query('select count(*)::int n from private.history_upsert_calls'))[0].n, 0);
  assert.equal((await query('select count(*)::int n from private.folder_completion_calls'))[0].n, 0);
  const replay = (await allowed('select public.request_archive_command_v1($1,$2,$3,$4) data', [actor,'active-1','archive',firstKey]))[0].data;
  assert.equal(replay.replayed, true);
  assert.equal((await query("select count(*)::int n from private.ph_request_archive_command_ledger"))[0].n, 1);

  const listed = (await allowed('select public.request_archive_list_v1($1,0,500) data', [actor]))[0].data;
  assert.equal(listed.total, 2);
  assert.equal(listed.rows.length, 2);
  assert.equal(listed.limit, 500);
  const restored = (await allowed('select public.request_archive_command_v1($1,$2,$3,$4) data', [actor,'active-1','restore','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb']))[0].data;
  assert.equal(restored.state, 'restored');
  const restoredRow = (await query("select req_archived, req_status, date_completed from public.ph_active_request where unique_id='active-1'"))[0];
  assert.deepEqual(restoredRow, { req_archived: false, req_status: 'Pending', date_completed: null });
  assert.deepEqual((await query("select delivery_state, history_event, req_archived, req_status, lotcode, snapshot from public.ph_request_history where unique_id='active-1'"))[0], historyBefore);
  assert.equal((await query('select count(*)::int n from private.folder_completion_calls'))[0].n, 0);
  const noHistoryArchive = (await allowed('select public.request_archive_command_v1($1,$2,$3,$4) data', [actor,'archived-1','restore','abababab-abab-4bab-8bab-abababababab']))[0].data;
  assert.equal(noHistoryArchive.state, 'restored');
  assert.equal((await query('select count(*)::int n from private.history_upsert_calls'))[0].n, 1);
  assert.deepEqual((await query("select delivery_state, history_event, req_archived, req_status, lotcode, snapshot from public.ph_request_history where unique_id='archived-1'"))[0], {
    delivery_state: 'pending', history_event: 'restored', req_archived: false, req_status: 'Pending', lotcode: 'canonical-lot', snapshot: { source: 'canonical' }
  });

  await assert.rejects(
    allowed('select public.request_archive_command_v1($1,$2,$3,$4)', [actor,'done-1','archive','cccccccc-cccc-4ccc-8ccc-cccccccccccc']),
    /REQUEST_ARCHIVE_COMPLETED_FORBIDDEN/
  );
  await assert.rejects(
    allowed('select public.request_archive_command_v1($1,$2,$3,$4)', [deniedActor,'active-1','archive','dddddddd-dddd-4ddd-8ddd-dddddddddddd']),
    /REQUEST_ARCHIVE_FORBIDDEN/
  );
  await assert.rejects(
    allowed('select public.request_archive_command_v1($1,$2,$3,$4)', [actor,'not-found','archive','eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee']),
    /REQUEST_ARCHIVE_NOT_FOUND/
  );
  console.log('Archive SQL passed: authorized reversible state flips, idempotency replay, fixed paged list, existing history preservation, missing-history creation, zero completion side effects, denied actor, completed-row rejection, and missing-row status.');
} finally {
  await db.close();
}
