-- Isolated CI fixture ONLY; never copied into the production migration set.
-- No passwords or remote accounts are provisioned by this file.
insert into auth.users(id,email)
values ('e2584b32-472c-4888-b592-394235050b5b','kayla_knepp@greenleafnursery.com'),
       ('961b0a0f-11a6-4db5-b066-582f772ab8e7','nelly_aguilar@greenleafnursery.com')
on conflict(id) do nothing;
insert into public.ph_app_users(id,username,role,disabled_at,must_change_password)
values (17,'kayla_knepp','ADMIN',null,false),(74,'nelly_aguilar','admin',null,false)
on conflict(id) do nothing;
insert into public.profiles(id,legacy_user_id,username,display_name,role,must_change_password)
values ('e2584b32-472c-4888-b592-394235050b5b',17,'kayla_knepp','Kayla Knepp','ADMIN',false),
       ('961b0a0f-11a6-4db5-b066-582f772ab8e7',74,'nelly_aguilar','Nelly Aguilar','admin',false)
on conflict(id) do nothing;

-- Current tables/columns absent from the selected historical CI replay.
-- DDL copied from the checked-in production baseline; disposable CI only.
CREATE TABLE IF NOT EXISTS public.ph_eval_assignment_rules (
    id bigint NOT NULL,
    sheet_id text DEFAULT ''::text NOT NULL,
    sheet_name text DEFAULT ''::text NOT NULL,
    sheet_row_number integer NOT NULL,
    assigned_to_raw text,
    assignedto text NOT NULL,
    warehousei text,
    itemcode text,
    contsize text,
    commonname text,
    locationcode text,
    source text,
    genusname text,
    normalized jsonb DEFAULT '{}'::jsonb NOT NULL,
    active boolean DEFAULT true NOT NULL,
    imported_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ci_handover_eval_rule_id ON public.ph_eval_assignment_rules(id);
ALTER TABLE public.ph_eval_assignment_rules ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ph_eval_assignment_rules FROM public, anon, authenticated;
GRANT ALL ON public.ph_eval_assignment_rules TO service_role;

CREATE TABLE IF NOT EXISTS public.ph_inventory_edit_requests (
    id text NOT NULL,
    status text DEFAULT 'Eval Update Needed'::text NOT NULL,
    workflow_stage text DEFAULT 'eval'::text NOT NULL,
    stage text,
    previous_stage text,
    stage_before_terminal text,
    request_type text DEFAULT 'inventory-edit'::text NOT NULL,
    priority_flag boolean DEFAULT false NOT NULL,
    inventory_edit_done boolean DEFAULT false NOT NULL,
    inventory_edit_completed_by text,
    inventory_edit_completed_by_display text,
    inventory_edit_completed_at timestamp with time zone,
    photo_data_done boolean DEFAULT false NOT NULL,
    photo_data_completed_by text,
    photo_data_completed_by_display text,
    photo_data_completed_at timestamp with time zone,
    source_unique_id text,
    master_unique_id text,
    source_view text,
    commonname text,
    contsize text,
    itemcode text,
    locationcode text,
    lotcode text,
    source text,
    ptravailable text,
    s_lts text,
    assignedto text,
    current_priority text,
    current_locationnote text,
    current_pulltagnotes text,
    current_holdstopcode text,
    current_holdreason text,
    requested jsonb DEFAULT '{}'::jsonb NOT NULL,
    changes jsonb DEFAULT '[]'::jsonb NOT NULL,
    snapshot jsonb DEFAULT '{}'::jsonb NOT NULL,
    holdreason text,
    reason text,
    supervisor_note text,
    approved_qty text,
    jd_approved_qty text,
    approved_by text,
    approved_by_display text,
    approved_at timestamp with time zone,
    sent_by text,
    sent_by_display text,
    sent_at timestamp with time zone DEFAULT now() NOT NULL,
    edited_by text,
    edited_by_display text,
    edited_at timestamp with time zone,
    stage_updated_by text,
    stage_updated_by_display text,
    stage_updated_at timestamp with time zone DEFAULT now() NOT NULL,
    handled_by text,
    handled_by_display text,
    handled_at timestamp with time zone,
    handler_note text,
    notification_stage text,
    notification_sent_at timestamp with time zone,
    inventory_edit_live boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.ph_master_inventory_user_assignments (
    master_unique_id text NOT NULL,
    assignedto text NOT NULL,
    assignment_source text DEFAULT 'assignedto_final'::text NOT NULL,
    source_assignedto text,
    itemcode text,
    lotcode text,
    locationcode text,
    source text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.ph_location_work_jobs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    idempotency_key text NOT NULL,
    title text NOT NULL,
    general_instructions text NOT NULL,
    status text DEFAULT 'open'::text NOT NULL,
    revision integer DEFAULT 1 NOT NULL,
    line_count integer DEFAULT 0 NOT NULL,
    resolved_line_count integer DEFAULT 0 NOT NULL,
    assigned_usernames text[] DEFAULT '{}'::text[] NOT NULL,
    assignment_event_id uuid,
    completion_event_id uuid,
    completion_recipient jsonb NOT NULL,
    created_by_profile_id uuid NOT NULL,
    created_by_username text NOT NULL,
    created_by_display text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_by_username text,
    completed_at timestamp with time zone,
    cancelled_by_username text,
    cancelled_at timestamp with time zone,
    CONSTRAINT ph_location_work_jobs_assignees_check CHECK (((cardinality(assigned_usernames) >= 1) AND (cardinality(assigned_usernames) <= 50))),
    CONSTRAINT ph_location_work_jobs_check CHECK (((resolved_line_count >= 0) AND (resolved_line_count <= line_count))),
    CONSTRAINT ph_location_work_jobs_completion_recipient_check CHECK ((jsonb_typeof(completion_recipient) = 'object'::text)),
    CONSTRAINT ph_location_work_jobs_general_instructions_check CHECK (((length(btrim(general_instructions)) >= 1) AND (length(btrim(general_instructions)) <= 8000))),
    CONSTRAINT ph_location_work_jobs_idempotency_check CHECK (((length(idempotency_key) >= 16) AND (length(idempotency_key) <= 240))),
    CONSTRAINT ph_location_work_jobs_line_count_check CHECK ((line_count >= 0)),
    CONSTRAINT ph_location_work_jobs_revision_check CHECK ((revision > 0)),
    CONSTRAINT ph_location_work_jobs_status_check CHECK ((status = ANY (ARRAY['open'::text, 'in_progress'::text, 'complete'::text, 'cancelled'::text]))),
    CONSTRAINT ph_location_work_jobs_title_check CHECK (((length(btrim(title)) >= 1) AND (length(btrim(title)) <= 240)))
);
CREATE TABLE IF NOT EXISTS public.ph_location_work_assignments (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    job_id uuid NOT NULL,
    profile_id uuid NOT NULL,
    username text NOT NULL,
    display_name text NOT NULL,
    email text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.ph_reserves (
    unique_id text NOT NULL,
    concat text,
    last_updated timestamp with time zone DEFAULT now(),
    assigned_to text,
    assignedto text,
    spec text,
    caliper text,
    pic_note text,
    sales_note text,
    av_note text,
    photo_link text,
    photo_name text,
    dock_spec text,
    dock_caliper text,
    dock_note text,
    dock_photo_link text,
    dock_photo_name text,
    date_completed text,
    flyer_cat text,
    flyer_title text,
    flyer_inst text,
    flyer_assigned text,
    flyer_notes text,
    flyer_photo_link text,
    flyer_photo_name text,
    flyer_completed text,
    initial_ptr text,
    loc_match_qty text,
    end_cap_folder text,
    end_cap_qty text,
    end_cap_level text,
    match text,
    item text,
    size text,
    container text,
    location text,
    lot text,
    warehouseid text,
    warehousename text,
    isreserve text,
    salesrepid text,
    salesrepname text,
    nationalaccountidgroup text,
    national_account_idgroup text,
    idgroup text,
    customeridentityid text,
    customername text,
    consigneeidentityid text,
    consigneename text,
    consigneecity text,
    consigneestate text,
    consigneezip text,
    tripnumber text,
    stopnumber text,
    zonecode text,
    tagcode text,
    transactionnumber text,
    purchaseordernumber text,
    extunitprice text,
    ordertotal text,
    requestdate text,
    stagename text,
    step text,
    customersku text,
    formattedupc text,
    printedcontainercode text,
    lotcode text,
    locationcode text,
    descriptorcode text,
    itemcode text,
    plantgroupcode text,
    sortname text,
    variety text,
    containersort text,
    qualitycode text,
    commonname text,
    quantityordered text,
    quantityshipped text,
    listprice text,
    unitprice text,
    handlingchargeperitem text,
    taggingchargeperitem text,
    combinedprice text,
    freightrateperitem text,
    landedretailprice text,
    holdstopcode text,
    holdstopreason text,
    salesnote text,
    fnsalesnote text,
    picknote text,
    planstart text,
    generalloadinstr text,
    invoicedate text,
    consigneeaddress_1 text,
    consigneeaddress_2 text,
    altshipcomment text,
    shiptotelephone_1 text,
    okloadinstructions text,
    txloadinstructions text,
    ncloadinstructions text,
    hlloadinstructions text,
    dock text,
    equiv_unit text,
    equiv_uom text,
    wingdingunits text,
    dropweight text,
    internalinvnote text,
    hardinesszone text,
    brand text,
    tagdeptnote text,
    ext_unit text,
    merch_shipped text,
    ext_unit_merch_shipped text,
    ext_eunit_shipped text,
    avg_price_eunit_shipped text,
    requestdateweek text,
    carrier text,
    suspend text,
    suspend_to text,
    qa_code text,
    grower text,
    nationalaccount text,
    sortnamevariety text,
    landed text,
    retailprice text,
    dock_num text,
    priority text,
    ptronhand text,
    ptrreviewed text,
    ptravailable text,
    season_supply text,
    s_lts text,
    itemspec text,
    season text,
    mcstatus text,
    hz text,
    intercopo text,
    insurancegroup text,
    si_lts text,
    a_lts text,
    ai_lts text,
    si_available text,
    holdstopenddate text,
    salesnote_1 text,
    contsize text,
    source text,
    desigitem text,
    desigcust text,
    desigloc text,
    filename text
);
CREATE TABLE IF NOT EXISTS public.ph_soc_master (
    unique_id text NOT NULL,
    concat text,
    last_updated timestamp with time zone DEFAULT now(),
    assignedto text,
    date_completed timestamp with time zone,
    dock_photo_link text,
    dock_photo_name text,
    dock_spec text,
    dock_caliper text,
    dock_note text,
    contsize text,
    warehouseid text,
    warehousename text,
    isreserve text,
    salesrepid text,
    salesrepname text,
    nationalaccount text,
    idgroup text,
    customeridentityid text,
    customername text,
    consigneeidentityid text,
    consigneename text,
    consigneecity text,
    consigneestate text,
    consigneezip text,
    tripnumber text,
    stopnumber text,
    zonecode text,
    tagcode text,
    transactionnumber text,
    purchaseordernumber text,
    extunitprice text,
    ordertotal text,
    requestdate text,
    stagename text,
    step text,
    customersku text,
    formattedupc text,
    printedcontainercode text,
    lotcode text,
    locationcode text,
    descriptorcode text,
    itemcode text,
    plantgroupcode text,
    sortnamevariety text,
    containersort text,
    qualitycode text,
    commonname text,
    quantityordered text,
    quantityshipped text,
    listprice text,
    unitprice text,
    handlingchargeperitem text,
    taggingchargeperitem text,
    combinedprice text,
    freightrateperitem text,
    landed text,
    retailprice text,
    holdstopcode text,
    holdstopreason text,
    salesnote text,
    fnsalesnote text,
    picknote text,
    planstart text,
    generalloadinstr text,
    invoicedate text,
    consigneeaddress_1 text,
    consigneeaddress_2 text,
    altshipcomment text,
    shiptotelephone_1 text,
    okloadinstructions text,
    txloadinstructions text,
    ncloadinstructions text,
    hlloadinstructions text,
    dock text,
    equiv_unit text,
    equiv_uom text,
    wingdingunits text,
    dropweight text,
    internalinvnote text,
    hardinesszone text,
    brand text,
    tagdeptnote text,
    ext_unit_merch_shipped text,
    ext_eunit_shipped text,
    avg_price_eunit_shipped text,
    requestdateweek text,
    carrier text,
    suspend text,
    suspend_to text,
    qa_code text,
    grower text,
    priority text,
    ptronhand text,
    ptrreviewed text,
    ptravailable text,
    season_supply text,
    s_lts text,
    itemspec text,
    season text,
    mcstatus text,
    hz text,
    intercopo text,
    insurancegroup text,
    si_lts text,
    a_lts text,
    ai_lts text,
    si_available text,
    holdstopenddate text,
    salesnote_1 text,
    spec text,
    caliper text,
    pic_note text,
    sales_note text,
    av_note text,
    photo_link text,
    photo_name text,
    flyer_cat text,
    flyer_title text,
    flyer_inst text,
    flyer_assigned text,
    flyer_notes text,
    flyer_photo_link text,
    flyer_photo_name text,
    flyer_completed text,
    initial_ptr text,
    loc_match_qty text,
    end_cap_folder text,
    end_cap_qty text,
    end_cap_level text,
    match text,
    dock_num text,
    source text,
    desigitem text,
    desigcust text,
    desigloc text,
    filename text
);
alter table public.ph_master_inventory add column if not exists eval_task_completed_at timestamptz;
alter table public.ph_master_inventory add column if not exists flyer_completed timestamptz;
alter table public.ph_master_inventory add column if not exists flyer_assigned text;
alter table public.ph_warehouse_assigned_items add column if not exists present_in_drive boolean not null default true;
create unique index if not exists ci_handover_inventory_link_key on public.ph_master_inventory_user_assignments(master_unique_id,assignedto,assignment_source);
create unique index if not exists ci_handover_location_profile_key on public.ph_location_work_assignments(job_id,profile_id);
alter table public.ph_reserves add column if not exists assignedto text;
alter table public.ph_reserves add column if not exists assigned_to text;
alter table public.ph_reserves add column if not exists flyer_assigned text;
alter table public.ph_reserves add column if not exists date_completed text;
alter table public.ph_reserves add column if not exists flyer_completed text;
alter table public.ph_soc_master add column if not exists assignedto text;
alter table public.ph_soc_master add column if not exists flyer_assigned text;
alter table public.ph_soc_master add column if not exists date_completed timestamptz;
alter table public.ph_soc_master add column if not exists flyer_completed text;

-- Required composite row type for the handover worker in the isolated replay.
CREATE TABLE IF NOT EXISTS public.ph_flyer_folder_rows (
    unique_id text NOT NULL,
    master_unique_id text,
    source_table text DEFAULT 'v2_master_inventory'::text,
    flyer_title text DEFAULT 'Unassigned'::text NOT NULL,
    flyer_assigned text,
    flyer_cat text,
    flyer_inst text,
    flyer_notes text,
    flyer_completed timestamp with time zone,
    assignedto text,
    date_completed timestamp with time zone,
    itemcode text,
    commonname text,
    contsize text,
    locationcode text,
    lotcode text,
    priority text,
    ptravailable text,
    s_lts text,
    holdstopcode text,
    plantgroupcode text,
    locationnote text,
    av_note text,
    match numeric,
    loc_match_qty numeric,
    spec text,
    caliper text,
    pick text,
    initial_ptr numeric,
    flyer_av_note text,
    flyer_match numeric,
    flyer_loc_match_qty numeric,
    flyer_spec text,
    flyer_caliper text,
    flyer_pick text,
    flyer_initial_ptr numeric,
    flyer_photo_link text,
    flyer_photo_name text,
    snapshot jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_by_username text,
    created_by_display text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ci_handover_flyer_uid ON public.ph_flyer_folder_rows(unique_id);
ALTER TABLE public.ph_flyer_folder_rows ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ph_flyer_folder_rows FROM public, anon, authenticated;
GRANT ALL ON public.ph_flyer_folder_rows TO service_role;
