-- HL PO parsed purchase-order rows.
-- Apps Script writes this table with the server-side Supabase service role.

create table if not exists public.ph_27f1_hl_po (
  id bigint generated by default as identity primary key,
  source_file_id text not null,
  source_file_name text,
  source_sheet_name text,
  report_date date,
  run_id text,
  row_index integer not null,
  item_code text,
  lot text,
  size text,
  common_name text,
  po_ordered numeric,
  genus text,
  po_comments text,
  lot_pend_rec numeric,
  seas_on_hand numeric,
  po_received numeric,
  po_remain numeric,
  created_at timestamptz not null default now(),
  imported_at timestamptz not null default now(),
  constraint ph_27f1_hl_po_source_file_row_key unique (source_file_id, row_index)
);

create unique index if not exists ph_27f1_hl_po_source_file_row_key
  on public.ph_27f1_hl_po (source_file_id, row_index);

create index if not exists ph_27f1_hl_po_report_date_idx
  on public.ph_27f1_hl_po (report_date desc);

create index if not exists ph_27f1_hl_po_item_code_idx
  on public.ph_27f1_hl_po (item_code);

alter table public.ph_27f1_hl_po enable row level security;

revoke all on table public.ph_27f1_hl_po from anon;
revoke all on table public.ph_27f1_hl_po from authenticated;
revoke all on sequence public.ph_27f1_hl_po_id_seq from anon;
revoke all on sequence public.ph_27f1_hl_po_id_seq from authenticated;

grant select, insert, update, delete on table public.ph_27f1_hl_po to service_role;
grant usage, select on sequence public.ph_27f1_hl_po_id_seq to service_role;

notify pgrst, 'reload schema';
