-- Stored HL PO Quantity Summary output.
-- Apps Script rebuilds this table from ph_master_inventory, ph_soc_master,
-- and ph_27f1_hl_po with the server-side Supabase service role.

create table if not exists public.ph_view_po_27f1_hl (
  id bigint generated by default as identity primary key,
  run_id text not null,
  row_index integer not null,
  itemcode text,
  commonname text,
  contsize text,
  locationcode text,
  priority text,
  lotcode text,
  holdstopcode text,
  holdstopreason text,
  total_quantity_ordered numeric,
  ptronhand numeric,
  total_ptronhand numeric,
  lot_pend_rec numeric,
  salesrepid text,
  salesrepname text,
  customername text,
  consigneename text,
  consigneestate text,
  stopnumber text,
  quantityordered numeric,
  requestdate text,
  stagename text,
  step text,
  dock text,
  po_remain numeric,
  created_at timestamptz not null default now(),
  built_at timestamptz not null default now(),
  constraint ph_view_po_27f1_hl_run_row_key unique (run_id, row_index)
);

create unique index if not exists ph_view_po_27f1_hl_run_row_key
  on public.ph_view_po_27f1_hl (run_id, row_index);

create index if not exists ph_view_po_27f1_hl_itemcode_idx
  on public.ph_view_po_27f1_hl (itemcode);

create index if not exists ph_view_po_27f1_hl_lotcode_idx
  on public.ph_view_po_27f1_hl (lotcode);

create index if not exists ph_view_po_27f1_hl_built_at_idx
  on public.ph_view_po_27f1_hl (built_at desc);

alter table public.ph_view_po_27f1_hl enable row level security;

revoke all on table public.ph_view_po_27f1_hl from anon;
revoke all on table public.ph_view_po_27f1_hl from authenticated;
revoke all on sequence public.ph_view_po_27f1_hl_id_seq from anon;
revoke all on sequence public.ph_view_po_27f1_hl_id_seq from authenticated;

grant select, insert, update, delete on table public.ph_view_po_27f1_hl to service_role;
grant usage, select on sequence public.ph_view_po_27f1_hl_id_seq to service_role;

notify pgrst, 'reload schema';
